apiVersion: v1
kind: Pod
metadata:
  name: finalproject
  labels:
    app: finalproject
spec:
  containers:
    - name: finalproject
      image: registry.hub.docker.com/amandastead44/finalproject
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  