apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproject
  labels:
    app: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: finalproject
      labels:
        app: web
    spec:
      containers:
        - name: finalproject
          image: amandastead44/finalproject
          imagePullPolicy: IfNotPresent
      restartPolicy: Always


  