apiVersion: v1
kind: Pod
metadata:
  name: final project
  labels:
    app: web
spec:
  containers:
    - name: final project
      image: nginx
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
